# Allows the following Apps access as they are allowed on our system

## Exclusions for Controlled Folder Access

Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\PeaZip\peazip.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Autodesk\Revit 2019\Revit.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Autodesk\Revit 2020\Revit.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Autodesk\Revit 2022\Revit.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Nitro\Pro 11\NitroPDF.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files (x86)\Tekla\Structural\Tedds\Tedds.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files (x86)\Adobe\Reader 11.0\Reader\AcroRd32.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Autodesk\AutoCAD 2020\acad.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Autodesk\AutoCAD 2022\acad.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Mesh Agent\MeshAgent.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\TacticalAgent\tacticalrmm.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\TacticalAgent\meshagent.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Autodesk\AutoCAD LT 2020\acadlt.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Autodesk\AutoCAD LT 2019\acadlt.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Autodesk\AutoCAD LT 2018\acadlt.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Autodesk\AutoCAD LT 2017\acadlt.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Autodesk\AutoCAD LT 2016\acadlt.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\Autodesk\AutoCAD 2016\acad.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Autodesk\AutoCAD LT 2015\acadlt.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Sage\Accounts\SBDDesktop.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\PROGRA~1\Nitro\PRO11~1\NitroPDF"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\ShareX\ShareX.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office 15\root\office15\winword.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office 15\root\office15\excel.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office 15\root\office15\powerpoint.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office 15\root\office15\powerpnt.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office 15\root\office15\outlook.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\root\Office16\EXCEL.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\root\Office16\winword.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\root\Office16\powerpoint.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\root\Office16\outlook.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\Office15\EXCEL.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\Office15\winword.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\Office15\powerpoint.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\Office15\outlook.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office\root\Office16\winword.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office\root\Office16\powerpoint.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office\root\Office16\outlook.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office\root\Office15\EXCEL.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office\root\Office15\winword.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office\root\Office15\powerpoint.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office\root\Office15\outlook.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Tekla\Structural\Fastrak\PFR.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\CCleaner\CCleaner64.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Tekla\Structural\Fastrak\tcd.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Autodesk\Revit 2022\Revit.exe" 
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\EvolutionM Client\client\wowclient.exe" 
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\WindowsApps\Microsoft.Office.Desktop.Excel_16051.14326.20348.0_x86__8wekyb3d8bbwe\Office16\excel.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Thesaurus Software\BrightPay UK 2021-22\brightpay.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Brother\iPrint&Scan\Brother iPrint&Scan\Brother iPrint&Scan.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Bullzip\PDF Printer\gui.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Dropbox\Client\Dropbox.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Bullzip\PDF Printer\gui.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Autodesk\DWG TrueView 2021 - English\dwgviewr.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Windows\System32\SearchProtocolHost.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Autodesk\Revit 2022\Revit.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Windows\System32\RuntimeBroker.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Adobe\Acrobat DC\Acrobat\Acrobat.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\root\Office16\EXCEL.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Draycir\Credit Hound\Credit Hound.exe"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\root\Office16\WINWORD.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\Office16\POWERPNT.EXE"
Add-MpPreference -ControlledFolderAccessAllowedApplications  "C:\Program Files (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE"

##Exclusions for Processes
Add-MpPreference -ExclusionPath  "C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE"
Add-MpPreference -ExclusionPath  "C:\Program Files (x86)\Microsoft Office\root\Office16\EXCEL.EXE"
Add-MpPreference -ExclusionPath  "C:\Program Files (x86)\Microsoft Office\root\Office16\WINWORD.EXE"
Add-MpPreference -ExclusionPath  "C:\Program Files (x86)\Microsoft Office\Office16\POWERPNT.EXE"
Add-MpPreference -ExclusionPath  "C:\Program Files (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE"
Add-MpPreference -ExclusionPath  "C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe"
Add-MpPreference -ExclusionPath  "C:\Program Files\PeaZip\peazip.exe"


Write-Output "Exclusions added to defender"